### ISSUE TITLE
质量分析的时候无法上传

### ISSUE THREAD

**Issue by hehaa** [WeBankFinTech/Qualitis#127]
com.webank.wedatasphere.qualitis.exception.UnExpectedRequestException: {&FAILED_TO_CALL_UPLOAD_API}
	at com.webank.wedatasphere.qualitis.service.impl.ApplicationServiceImpl.uploadDataSourceAnalysisResult(ApplicationServiceImpl.java:379) ~[web_task-0.9.0.jar:?]
	at com.webank.wedatasphere.qualitis.controller.ApplicationController.uploadDataSourceAnalysisResult(ApplicationController.java:122) ~[web_task-0.9.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76) ~[jersey-server-2.26.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148) [jersey-server-2.26.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191) [jersey-server-2.26.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:243) [jersey-server-2.26.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103) [jersey-server-2.26.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493) [jersey-server-2.26.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415) [jersey-server-2.26.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104) [jersey-server-2.26.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277) [jersey-server-2.26.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272) [jersey-common-2.26.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268) [jersey-common-2.26.jar:?]

![微信图片_20220721175638](https://user-images.githubusercontent.com/24778743/180186705-3def1259-d8fe-4d3e-a14d-0bda722f4085.jpg)
![1](https://user-images.githubusercontent.com/24778743/180186788-8408ab02-5b77-41ce-8c29-f610c816ec2f.jpg)

**Comment by hehaa** [comment]
生成路径要写当前用户名

**Comment by figodeng** [comment]
请教一下，你的linkis 创建的数据源是什么类型的？有什么需要注意的吗？我在linkis发布了数据源，在qualitis找不到

**Comment by isushao** [comment]
![image](https://user-images.githubusercontent.com/16602760/218402833-84f3481f-696a-4577-83d9-4f1fe2cfc3aa.png)
上传路径需要创建后才可使用，按照上图创建好。上传路径填写 /

**Comment by Tangjiafeng** [comment]
> 请教一下，你的linkis 创建的数据源是什么类型的？有什么需要注意的吗？我在linkis发布了数据源，在qualitis找不到

linkis 数据源管理无法直接在 Qualitis 中使用，当前的 release 版本仅支持 Hive。

**Comment by Flutemr** [comment]
你好，请问你是怎么解决的？
