### ISSUE TITLE
Schema-validation: missing table [qualitis_application]

### ISSUE THREAD

**Issue by liusy-bd** [WeBankFinTech/Qualitis#130]
运行启动命令 sh bin/start.sh  校验时找不到表 qualitis_application，数据库中是有该表的
![54b3832c3cb1316410bd49f11484a0d](https://user-images.githubusercontent.com/69708156/181227462-9ee09219-6ca2-45aa-b232-db18ee46e8dc.jpg)
![4b9f9f5b9b41d25c1e0c6b506695e6e](https://user-images.githubusercontent.com/69708156/181227480-65b7c46c-1efe-4597-9b48-549ecb4c17eb.jpg)

2022-07-27 18:35:31,386 WARN [main] webapp.WebAppContext doStart: Failed startup of context o.s.b.w.e.j.JettyEmbeddedWebAppContext@28f081ad{application,/,[file:///tmp/jetty-docbase.48400975
24185336354.8090/],UNAVAILABLE}
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'unFilterUrlFilterBean' defined in class path resource [com/webank/wedatasphere/qualitis/config/Filter
OrderConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.w
eb.servlet.FilterRegistrationBean]: Factory method 'unFilterUrlFilterBean' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creat
ing bean with name 'unFilterUrlFilter': Unsatisfied dependency expressed through field 'loginService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'loginServiceImpl': Unsatisfied dependency expressed through field 'userDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyExcept
ion: Error creating bean with name 'userDaoImpl': Unsatisfied dependency expressed through field 'userRepository'; nested exception is org.springframework.beans.factory.BeanCreationExceptio
n: Error creating bean with name 'userRepository': Cannot create inner bean '(inner bean)#6481dce5' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#6481dce5': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [qualitis_application]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627) ~[spring-beans-5.1.18.RELEASE.jar:5.1.18.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456) ~[spring-beans-5.1.18.RELEASE.jar:5.1.18.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1318) ~[spring-beans-5.1.18.RELEASE.jar:5.1.18.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158) ~[spring-beans-5.1.18.RELEASE.jar:5.1.18.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554) ~[spring-beans-5.1.18.RELEASE.jar:5.1.18.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514) ~[spring-beans-5.1.18.RELEASE.jar:5.1.18.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321) ~[spring-beans-5.1.18.RELEASE.jar:5.1.18.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.1.18.RELEASE.jar:5.1.18.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319) ~[spring-beans-5.1.18.RELEASE.jar:5.1.18.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) ~[spring-beans-5.1.18.RELEASE.jar:5.1.18.RELEASE]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:226) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:214) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:91) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:80) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:250) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]

**Comment by utopianet** [comment]
修改linkis-ps-publicservice.properties配置文件里为linkis.metadata.hive.permission.with-login-user-enabled=false试试

**Comment by Tangjiafeng** [comment]
> 修改linkis-ps-publicservice.properties配置文件里为linkis.metadata.hive.permission.with-login-user-enabled=false试试

Qualitis 的启动应该和 Linkis 配置没有直接的关系的。

**Comment by Tangjiafeng** [comment]
建议将配置改为：
spring:
  jpa:
    hibernate:
      ddl-auto: update
      
项目启动会自动刷新表结构。
