### ISSUE TITLE
Schema specific part is opaque.

### ISSUE THREAD

**Issue by alexander1005** [WeBankFinTech/Qualitis#134]
a/db
2022-08-15 15:47:57,149 ERROR [qtp808485741-60] controller.MetaDataController getUserDbByCluster: Failed to get database by cluster: demoCluster, caused by: Schema specific part is opaque.
java.lang.IllegalArgumentException: Schema specific part is opaque.
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.checkSsp(JerseyUriBuilder.java:714) ~[jersey-common-2.26.jar:?]
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:356) ~[jersey-common-2.26.jar:?]
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:72) ~[jersey-common-2.26.jar:?]
获取数据源失败
本项目用的spring-boot版本为2.0.15,目前linkis 1.1.1 springboot已到2.3.请问是要降级linkis版本吗

**Comment by KangTomwk** [comment]
hi，我也遇到相同问题，导致添加规则校验 无法选择库名表名，你解决了吗

**Comment by yemengisyou** [comment]
Hello, I also have the same problem. Have you solved it? Thank you.

**Comment by yemengisyou** [comment]
> hi，我也遇到相同问题，导致添加规则校验 无法选择库名表名，你解决了吗

你好，请问你解决了吗

**Comment by cquliaoli** [comment]
<img width="547" alt="qualitis" src="https://github.com/WeBankFinTech/Qualitis/assets/9543666/1581e1cb-65bb-4eee-89fb-f2ae72fcd3c8">
检测集群地址配置 url 是否完整

**Comment by Tangjiafeng** [comment]
依赖部署的 Linkis 具备数据源服务能力，优先确认 Linkis Gateway 配置正确，先做基础的 Hive 规则配置验证，然后验证 Mysql 规则的流程。
