### ISSUE TITLE
hive metadata refresh error when its db is postgresql

### ISSUE THREAD

**Issue by starqiu** [WeBankFinTech/Qualitis#2]
**Describe the bug**
when my hive metadata db is postgresql，and i create metadata table use such grammar （table name add ""）
```sql
CREATE TABLE "GLOBAL_PRIVS" (
    "USER_GRANT_ID" bigint NOT NULL,
    "CREATE_TIME" bigint NOT NULL,
    "GRANT_OPTION" smallint NOT NULL,
    "GRANTOR" character varying(128) DEFAULT NULL::character varying,
    "GRANTOR_TYPE" character varying(128) DEFAULT NULL::character varying,
    "PRINCIPAL_NAME" character varying(128) DEFAULT NULL::character varying,
    "PRINCIPAL_TYPE" character varying(128) DEFAULT NULL::character varying,
    "USER_PRIV" character varying(128) DEFAULT NULL::character varying
);
```
when i  click metadataManagement, it will try to get clusters, select cluster ,will get dbs. The exception is :
```java

2019-12-05 13:49:50,006 INFO [DefaultQuartzScheduler_Worker-3] cron.RefreshMetaData: Start to refresh meta data of cluster: BDAP
2019-12-05 13:49:50,010 ERROR [DefaultQuartzScheduler_Worker-3] cron.RefreshMetaData: Failed to execute sql
org.postgresql.util.PSQLException: ERROR: relation "dbs" does not exist
  Position: 18
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:231) ~[postgresql-42.1.4.jar:42.1.4]
        at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111) ~[HikariCP-2.7.9.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java) ~[HikariCP-2.7.9.jar:?]
        at com.webank.wedatasphere.qualitis.hive.dao.impl.HiveMetaDataDaoImpl.getHiveDbByCluster(HiveMetaDataDaoImpl.java:55) ~[core_meta_data-0.5.0.jar:?]
        at com.webank.wedatasphere.qualitis.hive.cron.RefreshMetaData.getAndSaveDbs(RefreshMetaData.java:159) ~[core_meta_data-0.5.0.jar:?]
        at com.webank.wedatasphere.qualitis.hive.cron.RefreshMetaData.execute(RefreshMetaData.java:107) [core_meta_data-0.5.0.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.1.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.1.jar:?]
2019-12-05 13:49:50,011 INFO [DefaultQuartzScheduler_Worker-3] core.JobRunShell: Job Meta data refresh job group.Meta data refresh job threw a JobExecutionException:
org.quartz.JobExecutionException: Failed to execute sql
        at com.webank.wedatasphere.qualitis.hive.cron.RefreshMetaData.execute(RefreshMetaData.java:115) ~[core_meta_data-0.5.0.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.1.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.1.jar:?]

```

The bug code is `HiveMetaDataDaoImpl` , `String sql = "SELECT NAME FROM DBS";` should be `String sql = "SELECT \"NAME\" FROM \"DBS\"";` for my case. same as get tables and columns.

the root question is use normal database access instead of hive metadata service or ORM .

qualitis version: release-0.5.0

**Comment by howeye** [comment]
You are right. We will soon repair it in the near release.

**Comment by howeye** [comment]
Can we chat it with wechat?
There is some problems i want to ask for you.
My wechat: 18819253626

**Comment by starqiu** [comment]
of course，it's my pleasure！
